version: '3.3'
services:
  ipfs:
    image: ipfs/go-ipfs:v0.4.13
    environment:
      - LIBP2P_FORCE_PNET=1
    command: ["daemon", "--migrate=true", "--enable-gc", "--enable-pubsub-experiment"]
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '1024M'
      labels:
        - traefik.frontend.rule=Host:ipfs.trading-post.club
        - traefik.frontend.entryPoints=http,https
        - "traefik.frontend.auth.basic=computes:$$apr1$$ytmVb2GX$$ebtIUPCG1JFWKbPOtHv.n1"
        - traefik.port=5001
    volumes:
      - ./config/ipfs-data:/data/ipfs
    ports:
      - "4001:4001"
    networks:
      - ipfs
  ipfs-pinning-service:
    image: computes/ipfs-pinning-service:v4.1.1
    env_file: './config/ipfs-pinning-service.env'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '20M'
    networks:
      - ipfs
  goslow4me:
    image: royvandewater/rustygoslow4me:v1.1.3
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 10M
      labels:
        - traefik.frontend.rule=HostRegexp:goslow4.me,{subdomain:[a-zA-Z0-9_]+}.goslow4.me
        - traefik.frontend.entryPoints=http,https
        - traefik.port=80
    networks:
      - goslow4me
  trading-post:
    image: royvandewater/trading-post:v6.5.3
    env_file: './config/trading-post.env'
    depends_on:
      - mongo
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 10M
      labels:
        - traefik.frontend.rule=Host:trading-post.club
        - traefik.frontend.entryPoints=http,https
        - traefik.port=80
    networks:
      - trading-post
  mongo:
    image: mongo
    deploy:
      resources:
        limits:
          memory: 100M
    volumes:
      - ./config/mongo-data:/data/db
    networks:
      - trading-post
  traefik:
    image: traefik:v1.5
    deploy:
      resources:
        limits:
          memory: 30M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./config/traefik/acme.json:/etc/traefik/acme/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8181:8181"
    networks:
      - goslow4me
      - ipfs
      - trading-post
networks:
  goslow4me:
    attachable: true
  ipfs:
    attachable: true
  trading-post:
    attachable: true
